# Generated by Django 4.2.3 on 2023-07-17 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 16, 21, 29, 37, 546407)),
        ),
    ]
